OK_APPLICATION_ID: int = 1
OK_ACCESS_TOKEN: any
OK_SESSION_SECRET_KEY: any
OK_APPLICATION_KEY: any
OK_APPLICATION_SECRET_KEY: any

OK_GROUP_ID: any
OK_TOPIC_URL_PATTERN: any
OK_MAXIMUM_TOPICS_PER_WEEK: any

VK_SAFE_KEY: any
VK_APP_ID: any
VK_USER_TOKEN: any
VK_OAUTH_TOKEN: any
VK_VERSION: any

VK_CLUB_ID: any
VK_DOMAIN: any
VK_POST_URL_PATTERN: any
VK_MAXIMUM_TOPICS_PER_WEEK: any

TG_PHONE: any
TG_API_ID: any

TG_API_HASH: any
TG_AM_API_ID: any

TG_AM_API_HASH: any

TG_CHANNEL_NAME: any
TG_CHANNEL_ID: int
TG_POST_URL_PATTERN: any
TG_MAXIMUM_TOPICS_PER_WEEK: int

OK_SHEET_NAME: any
VK_SHEET_NAME: any
TG_SHEET_NAME: any

OK_COLUMNS: any
VK_COLUMNS: any
TG_COLUMNS: any

LAST_MON: any
CUR_MON: any
